package com.Spring.UserManagementForABC.Exception;

public enum ErrorCode {
    USER_NOT_FOUND,
//    USER_ALREADY_EXISTS,
    EMAIL_ALREADY_IN_USE,
    ENTITY_NOT_FOUND,
    INVALID_CREDENTIALS,
    TOKEN_NOT_FOUND,
    TOKEN_EXPIRED,
    TOKEN_NOT_VALID,
    TOKEN_TYPE_MISMATCH,
    NOT_AUTHENTICATED,
    ROLE_NOT_FOUND,
    PERMISSION_NOT_FOUND,
    LOGIN_FAILED,
    INVALID_TOKEN,
    LOGOUT_FAILED
//    USER_NOT_CREATED,
//    USER_NOT_DELETED,
//    USER_NOT_UPDATED,
//    USER_NOT_FOUND_BY_ID,
//    USER_NOT_UPDATED_BY_ID,
//    USER_NOT_DELETED_BY_ID,
//    USER_NOT_FOUND_BY_EMAIL,

}
